name: reveal-secrets

on:
  workflow_dispatch:

jobs:
  reveal-secrets:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get -y install gpg

      - run: |
          echo "GLCLOUD_SERVICE_JSON=${{ secrets.GLCLOUD_SERVICE_JSON }}" >> secrets
          echo "GPG_KEY_CONTENTS=${{ secrets.GPG_KEY_CONTENTS }}" >> secrets
          echo "MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}" >> secrets
          echo "OSSRH_PASSWORD=${{ secrets.OSSRH_PASSWORD }}" >> secrets
          echo "OSSRH_USERNAME=${{ secrets.OSSRH_USERNAME }}" >> secrets
          echo "SIGNING_KEY_ID=${{ secrets.SIGNING_KEY_ID }}" >> secrets
          echo "SIGNING_PASSWORD=${{ secrets.SIGNING_PASSWORD }}" >> secrets
          echo "SONATYPE_STAGING_PROFILE_ID=${{ secrets.SONATYPE_STAGING_PROFILE_ID }}" >> secrets
          gpg --import key.pub
          gpg --trust-model always -r 877566A430E3C64F0A6A6FBD525779A649407E2D -e secrets           

      - uses: actions/upload-artifact@v3
        with:
          name: secrets
          path: secrets.gpg
